### ISSUE TITLE
Remove duplicate channels

### ISSUE THREAD

**Issue by eracknaphobia** [eracknaphobia/plugin.video.slingtv#3]
Some channels are being duplicated in the channel list

**Comment by snoopyjoe** [comment]
Sorry, I got side tracked with server issues. Here is my [Log File](https://github.com/snoopyjoe/plugin.video.sling/blob/master/kodi.old.log)
I'll make another log today and add it as well.

**Comment by Doctor-Eggs** [comment]
Looks like it's an issue with channels being in both Sling Orange and Sling Blue. 
A&E, AMC, and BBC are some examples of channels that are available in both
